config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # path("news/", TemplateView.as_view(template_name="pages/news.html"), name="news"),
    # path("blogs/", TemplateView.as_view(template_name="pages/blogs.html"), name="blogs"),
    # path("quora/", TemplateView.as_view(template_name="pages/quora.html"), name="quora"),
    path("chat/", TemplateView.as_view(template_name="pages/chat.html"), name="chat"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    ### 第三方路由
    re_path(r'mdeditor/', include('mdeditor.urls')),
    re_path(r'comments/', include('django_comments.urls')),
    # User management
    path("users/", include("mydjango.users.urls", namespace="users")),
    path("news/", include("mydjango.news.urls", namespace="news")),
    path("blogs/", include("mydjango.blogs.urls", namespace="blogs")),
    path("quora/", include("mydjango.quora.urls", namespace="quora")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

mydjango/blogs/urls.py
from django.urls import path
from django.views.generic import TemplateView

from mydjango.blogs import views

app_name = "blogs"

urlpatterns = [
    path("", views.ArticleListView.as_view(), name="list"),
    path("articel-creat/", views.ArticleCreateView.as_view(), name="create"),
    path("get-drafts/", views.DraftListView.as_view(), name="drafts"),
    path("article/<str:slug>/", views.ArticleDetailView.as_view(), name="detail"),
    path("article-update/<int:pk>/", views.ArticleUpdateView.as_view(), name="update"),
]

mydjango/news/urls.py
from django.urls import path

from mydjango.news import views

app_name = "news"

urlpatterns = [
    path("", views.NewsListView.as_view(), name="list"),
    path("post-news/", views.post_news, name="post_news"),
    path("delete/<str:pk>/", views.NewDeleteView.as_view(), name="delete_news"),
    path("like/", views.like, name="post_like"),
    path("post-reply/", views.post_reply, name="post_reply"),
    path("get-replies/", views.get_replies, name="get_replies"),
    # path("reply/", views.reply, name="post_reply"),
    # path("~redirect/", view=user_redirect_view, name="redirect"),
    # path("~update/", view=user_update_view, name="update"),
    # # path("<str:username>/", view=user_detail_view, name="detail"),
    # path("<str:username>/", view=user_detail_view, name="detail"),
]

mydjango/quora/urls.py
from django.urls import path

from mydjango.quora import views

app_name = "quora"

urlpatterns = [
    path("", views.QuestionListView.as_view(), name="all-questions"),
    path("correct-answered-questions", views.CorrectAnsweredQuestionListView.as_view(), name="correct-answered-questions"),
    path("uncorrect-answered-questions", views.UncorrectAnsweredQuestionListView.as_view(), name="uncorrect-answered-questions"),

]

mydjango/blogs/models.py
import uuid

from django.conf import settings
from django.db import models

# Create your models here.
from django.db.models import Count
from slugify import slugify

from taggit.managers import TaggableManager
from mdeditor.fields import MDTextField

# class ExampleModel(models.Model):
#     name = models.CharField(max_length=10)
#     content = MDTextField()

class ArticleCategory(models.Model):
    """定义文章类型"""
    catname = models.CharField(max_length=50, verbose_name="类别名称")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    updated_at = models.DateTimeField(auto_now=True, verbose_name="更新时间")

    def __str__(self):
        return self.catname

    class Meta:
        verbose_name = "文章类别"
        verbose_name_plural = verbose_name


class ArticleQuerySet(models.query.QuerySet):
    """自定义queryset ，提高模型的可用性"""

    def get_published(self):
        """返回已发表的文章"""
        return self.filter(status="P").order_by('-updated_at')

    def get_drafts(self):
        """返回草稿箱的文章"""
        return self.filter(status="D").order_by('-updated_at')

    def get_counted_tag(self):
        """返回已发表的文章中，每一个标签的数量(大于0的)"""
        tag_dict ={}
        query = self.filter(status="P").annotate(tagged=Count('tags')).filter(tags__gt=0)
        for obj in query:
            for tag in obj.tags.names():
                if tag not in tag_dict:
                    tag_dict[tag] = 1
                else:
                    tag_dict[tag] = -1
        return tag_dict.items()


class Article(models.Model):
    STATUS = (("D", "Draft"), ("P", "Published"))
    status = models.CharField(max_length=1, choices=STATUS, default='D', verbose_name="状态")
    category = models.ForeignKey(ArticleCategory, verbose_name="文章类别",
                                 null=True, blank=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, related_name="author",
                             on_delete=models.SET_NULL, verbose_name="作者")
    title = models.CharField(max_length=255, blank=False, null=False, unique=False, verbose_name="文章标题")
    cover = models.ImageField(upload_to="blogs/covers/%y/%m/%d", verbose_name="文章封面")
    abstract = models.CharField(max_length=255, null=True, blank=True, verbose_name="文章摘要", default="此文章还没有摘要")
    content = MDTextField(verbose_name="文章内容")
    slug = models.SlugField(max_length=255, null=True, blank=True, verbose_name="(url)别名")
    tags = TaggableManager(help_text="多个标签使用英文逗号(,)隔开", verbose_name="文章标签")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    updated_at = models.DateTimeField(auto_now=True, verbose_name="更新时间")

    objects = ArticleQuerySet.as_manager()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name

    def save(self, *args, **kwargs):
        if not self.slug:
            # 根据作者和标题生成文章url别名
            self.slug = slugify(self.title + self.user.username +"-" + uuid.uuid4().__str__()[0:8])

        super(Article, self).save(*args, **kwargs)

mydjango/blogs/forms.py
from django import forms
from mdeditor.fields import MDTextFormField
from mydjango.blogs.models import Article


class ArticleForm(forms.ModelForm):
    content = MDTextFormField()

    class Meta:
        model = Article
        fields = ['category', "title", "abstract", "content", "cover", "tags", "status"]

mydjango/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):

    error_message = admin_forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

mydjango/blogs/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView
from mydjango.blogs.forms import ArticleForm
from mydjango.blogs.models import Article, ArticleCategory
from mydjango.utils import AuthorRequiredMixin


class ArticleListView(ListView):
    """已发布的文章列表"""
    model = Article
    paginate_by = 5
    content_object_name = "article_list"
    template_name = "blogs/article_list.html"

    def get_queryset(self):
        return Article.objects.get_published()

    def get_context_data(self, *args, **kwargs):
        context = super(ArticleListView, self).get_context_data(*args, **kwargs)
        context['article_categories'] = ArticleCategory.objects.all()
        context['popular_tags'] = Article.objects.get_counted_tag()
        return context


class DraftListView(ArticleListView):

    def get_queryset(self, **kwargs):
        return Article.objects.get_drafts()

class ArticleCreateView(LoginRequiredMixin, CreateView):
    """创建文章"""
    model = Article
    form_class = ArticleForm
    template_name_suffix = "_create_form"
    template_name = "blogs/article_create_form.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ArticleCreateView, self).form_valid(form)

    # success_url = reverse_lazy('blogs:list')

    def get_success_url(self):
        message = "您的文章已经创建成功"
        messages.success(self.request,message)
        return reverse_lazy('blogs:list')

class ArticleDetailView(DetailView):
    """文章详情"""
    model = Article
    template_name =  'blogs/article_detail.html'
    context_object_name = 'article'

class ArticleUpdateView(LoginRequiredMixin, AuthorRequiredMixin, UpdateView):
    """用户更新文章"""
    model = Article
    form_class = ArticleForm
    template_name_suffix = "_update_form"
    template_name = "blogs/article_update_form.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ArticleUpdateView, self).form_valid(form)

    def get_success_url(self):
        message = "您的文章已经修改成功"
        messages.success(self.request,message)
        return reverse_lazy('blogs:detail', kwargs={'slug':self.get_object().slug})

mydjango/news/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseBadRequest, HttpResponse, JsonResponse
from django.shortcuts import render
from django.contrib.auth.decorators import  login_required
from django.template.loader import  render_to_string
from django.urls import reverse, reverse_lazy
from django.views.decorators.http import require_http_methods
# noinspection PyUnresolvedReferences
from mydjango.utils import ajax_required, AuthorRequiredMixin
# Create your views here.
from django.views.generic import ListView, DeleteView
from mydjango.news.models import News



class NewsListView(ListView):
    """新闻列表页"""
    # model = News
    # queryset = News.objects.filter(reply=False).all()
    paginate_by = 10
    template_name = "news/news_list.html"
    content_object_name = 'news_list'

    def get_queryset(self, *kwargs):
        return News.objects.filter(reply=False).all()

    # def get_context_data(self, *, object_list=None, **kwargs):
    #     context = super(NewsListView, self).get_context_data()
    #     context['importantNews'] = News
    #     return context

@login_required
@ajax_required
@require_http_methods(['POST'])
def post_news(request):
    """发送ajax post请求"""
    newsContent = request.POST['news_content'].strip()
    if newsContent:
        news = News.objects.create(user=request.user, content=newsContent)
        html = render_to_string('news/news_single.html', {'news': news, 'request': request})
        return HttpResponse(html)
    else:
        return HttpResponseBadRequest("内容不能为空！")

class NewDeleteView(LoginRequiredMixin, AuthorRequiredMixin, DeleteView):
    """删除一条新闻记录"""
    model = News
    template_name = 'news/news_confirm_delete.html'
    success_url = reverse_lazy('news:list')

@login_required
@ajax_required
@require_http_methods(['POST'])
def like(request):
    """点赞，相应ajax post请求"""
    news_id = request.POST['newsId']
    news = News.objects.get(pk=news_id)
    # 取消或者添加点赞
    news.switch_like(request.user)
    # 返回点赞数量
    return JsonResponse({"liker_count": news.likers_count()})

@login_required
@ajax_required
@require_http_methods(['POST'])
def post_reply(request):
    """发送回复ajax post请求"""
    print(request.POST['replyContent'])
    replyContent = request.POST['replyContent'].strip()
    parentId = request.POST['newsid']
    parent = News.objects.get(pk=parentId)
    # print(replyContent)
    if replyContent:
        parent.reply_this(request.user, replyContent)
        return JsonResponse({"newsid": parent.pk, "replies_count": parent.replies_count()})
    else:
        return HttpResponseBadRequest("内容不能为空！")

@ajax_required
@require_http_methods(['POST', 'GET'])
def get_replies(request):
    """返回新闻的评论"""
    news_id = request.GET['newsId']
    news = News.objects.get(pk=news_id)
    # render_to_string() 表示加载模板 填充数据，返回字符串
    replies_html = render_to_string("news/reply_list.html", {"replies": news.get_children()})
    # print(replies_html)
    return JsonResponse({
        "uuid": news_id,
        "replies_html": replies_html,
    })

mydjango/quora/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView
from mydjango.quora.models import Question


class QuestionListView(ListView):
    """所有问题列表"""
    model = Question
    paginate_by = 20
    context_object_name = 'questions-list'
    template_name = 'quora/question_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(QuestionListView, self).get_context_data()
        context["popular_tags"] = Question.objects.get_counted_tag()
        return context

class CorrectAnsweredQuestionListView(QuestionListView):
    """已有采纳答案的问题列表"""
    def get_queryset(self):
        return Question.objects.get_correct_answered()

class UncorrectAnsweredQuestionListView(QuestionListView):
    """还没有被采纳答案的问题列表"""
    def get_queryset(self):
        return Question.objects.get_uncoreect_answered()

mydjango/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    pk_url_kwarg = 'pk'
    template_name = 'users/user_detail.html'

user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["nickname", "job", "introduction", "avatar", "address", "birthday", "personal_url", "weibo", "zhihu", "github", "linkedin"]
    template_name = 'users/user_form.html'

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)
        # return self.request.user

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

mydjango/templates/news/news_confirm_delete.html
{% extends "base.html" %}
{% load static  thumbnail %}
{% block title %}
  删除新闻| {{ block.super }}
{% endblock %}
{% block content %}
  <h3>确定要删除吗？</h3>
  <form method="post" action="{% url 'news:delete_news' news.pk %}" >
  {% csrf_token %}
  <button class="btn btn-danger" type="submit">删除</button>
  </form>
{% endblock %}

mydjango/templates/news/news_form_modal.html
<!-- Modal -->
<div class="modal fade" id="newsFormModal" tabindex="-1" role="dialog" aria-labelledby="newsFormModalTitle"
     aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" >发布新闻动态</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id="postNewsFrom" role="form" method="post" action="#" onsubmit="return false">
          {% csrf_token %}
          <div class="form-group">
            <label for="newsInput"></label>
            <textarea id="newsInput" name="news_content" rows="5" class="form-control"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" id="postNews" class="btn btn-primary">
          <i class="fa fa-paper-plane" aria-hidden="true"></i>发送
        </button>
        <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
      </div>
    </div>
  </div>
</div>

mydjango/templates/news/news_list.html
{% extends "base.html" %}
{% load static  thumbnail %}
{% block title %}
  新闻列表 | {{ block.super }}
{% endblock %}
{% block css%}
{% endblock %}
{% block content %}
  <div class="my-3"></div>
  <div class="row">
    <div class="col-md-8">
      <ul class="stream">
        {#    {% for news in news_list %}#}
        {% for news_item in news_list %}
          {% include "news/news_single.html" with news=news_item %}
        {% endfor %}
       {% include 'pagination.html' %}
      </ul>
    </div>
    <div class="col-md-4">
      <div class="card" style="width: 18rem;">
        <button type="button" class="btn btn-primary"
                data-toggle="modal"
                data-target="#newsFormModal">
          发布新闻动态
        </button>
      </div>
      <div class="card mt-3" style="width: 18rem;">
{#        <img src="..." class="card-img-top" alt="...">#}
        <div class="card-body">
          <h5 class="card-title">今日话题</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's
            content.</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>

      <div class="card mt-4" style="width: 18rem;">
{#        <img src="..." class="card-img-top" alt="...">#}
        <div class="card-body">
          <h5 class="card-title">本周要闻</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's
            content.</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

{% block modal %}
  {% include "news/news_form_modal.html" %}
  {% include "news/reply_form_modal.html" %}
  {% include "news/reply_list_modal.html" %}
{% endblock %}
{% block javascript %}
  <script src="{% static 'js/news.js' %}" type="text/javascript"></script>
{% endblock %}

mydjango/templates/news/news_single.html
{% load static thumbnail humanize %}
<li class="news-item" style="list-style: none" news-id="{{ news.pk }}">
  <div class="media">
    {% thumbnail news.user.avatar "x100" as im %}
      <img src="{{ im.url }}" style="border-radius: 50%" alt="用户头像" class="align-self-start mr-3"/>
    {% empty %}
      <img src="{% static 'images/user.png' %}" style="border-radius: 50%;height: 100px" class="align-self-start mr-3"
           alt="没有头像"/>
    {% endthumbnail %}
    <div class="media-body">
      <h5 class="mt-0">{{ news.user.get_profile_name }}
        {% if request.user.username == news.user.username %}
          <a href="{% url 'news:delete_news' news.pk %}"><i class="fa fa-times pull-right" title="点击删除这条动态"></i></a>
        {% endif %}

      </h5>
      <p> {{ news.content }}</p>
      <div class="interaction">
        <a href="#" class="like pull-right"
           title="{% for item in news.get_likers %}{{ item.get_profile_name }}&#10;{% endfor %}">
          {% if request.user in news.get_likers %}
            <i class="heart fa fa-heart" aria-hidden="true"></i>
          {% else %}
            <i class="heart fa fa-heart-o" aria-hidden="true"></i>
          {% endif %}
          <span class="like-count">{{ news.likers_count }}</span>
        </a>
        <a href="#" class="reply pull-right mr-3" data-toggle="modal" data-target="#replyListModal">
          <i class="fa fa-comment-o " aria-hidden="true"></i>
          <span class="reply-count">{{ news.replies_count }}</span>
        </a>
        <button type="button" class="btn btn-sm btn-outline-primary pull-right mr-3" data-toggle="modal"
                data-target="#replyFormModal"
                data-newsid="{{ news.pk }}"
                data-who="@{{ news.user.username }}">回复
        </button>
        <span class="timestamp pull-left">{{ news.updated_at|naturaltime }}</span>
      </div>
    </div>
  </div>
  {#        {{ news.reply }}------{{ news.content }}#}
</li>
<hr/>

mydjango/templates/news/reply_form_modal.html
<div class="modal fade" id="replyFormModal" tabindex="-1" role="dialog" aria-labelledby="replyFormModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="replyFormModalLabel">新的回复</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id="postReplyForm" role="form" method="post" action="#" onsubmit="return false">
          {% csrf_token %}
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">新闻发布者:</label>
            <input type="text" class="recipient form-control" id="recipient-name" name="recipient">
          </div>
          <div class="form-group">
            <label for="newsid" class="col-form-label">新闻 ID:</label>
            <input type="text" class="newsid form-control" id="newsid" name="newsid">
          </div>
          <div class="form-group">
            <label for="reply-content" class="col-form-label">回复内容:</label>
            <textarea class="form-control" id="reply-content" name="replyContent"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
        <button type="button" class="btn btn-primary" id="postReply">提交回复</button>
      </div>
    </div>
  </div>
</div>

mydjango/templates/news/reply_list.html
{% load static thumbnail humanize %}
<ul class="stream">
  {% for reply in replies %}
    <li style="list-style:none" class="reply-item" reply-id="{{ reply.pk }}">
      <div class="media">
        <div class="media-body">
          <h5 class="mt-0">{{ reply.user.get_profile_name }}</h5>
          <p> {{ reply.content }}</p>
          <div class="interaction">
            <span class="timestamp pull-left">{{ reply.updated_at|naturaltime }}</span>
          </div>
        </div>
      </div>
      <hr/>
    </li>
  {% endfor %}
</ul>

mydjango/templates/news/reply_list_modal.html
{#<!-- Button trigger modal -->#}
{#<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#replyListModal">#}
{#  Launch demo modal#}
{#</button>#}

<!-- Modal -->
<div class="modal fade" id="replyListModal" tabindex="-1" role="dialog" aria-labelledby="replyListModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="replyListModalTitle">评论列表</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">x</span>
        </button>
      </div>
      <div class="modal-body">

      </div>
      <div class="modal-footer">
{#        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>#}
{#        <button type="button" class="btn btn-primary">Save changes</button>#}
      </div>
    </div>
  </div>
</div>