config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # path("news/", TemplateView.as_view(template_name="pages/news.html"), name="news"),
    # path("blogs/", TemplateView.as_view(template_name="pages/blogs.html"), name="blogs"),
    # path("quora/", TemplateView.as_view(template_name="pages/quora.html"), name="quora"),
    path("chat/", TemplateView.as_view(template_name="pages/chat.html"), name="chat"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    ### 第三方路由
    re_path(r'mdeditor/', include('mdeditor.urls')),
    re_path(r'comments/', include('django_comments.urls')),
    # User management
    path("users/", include("mydjango.users.urls", namespace="users")),
    path("news/", include("mydjango.news.urls", namespace="news")),
    path("blogs/", include("mydjango.blogs.urls", namespace="blogs")),
    path("quora/", include("mydjango.quora.urls", namespace="quora")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

mydjango/blogs/urls.py
from django.urls import path
from django.views.generic import TemplateView

from mydjango.blogs import views

app_name = "blogs"

urlpatterns = [
    path("", views.ArticleListView.as_view(), name="list"),
    path("articel-creat/", views.ArticleCreateView.as_view(), name="create"),
    path("get-drafts/", views.DraftListView.as_view(), name="drafts"),
    path("article/<str:slug>/", views.ArticleDetailView.as_view(), name="detail"),
    path("article-update/<int:pk>/", views.ArticleUpdateView.as_view(), name="update"),
]

mydjango/news/urls.py
from django.urls import path

from mydjango.news import views

app_name = "news"

urlpatterns = [
    path("", views.NewsListView.as_view(), name="list"),
    path("post-news/", views.post_news, name="post_news"),
    path("delete/<str:pk>/", views.NewDeleteView.as_view(), name="delete_news"),
    path("like/", views.like, name="post_like"),
    path("post-reply/", views.post_reply, name="post_reply"),
    path("get-replies/", views.get_replies, name="get_replies"),
    # path("reply/", views.reply, name="post_reply"),
    # path("~redirect/", view=user_redirect_view, name="redirect"),
    # path("~update/", view=user_update_view, name="update"),
    # # path("<str:username>/", view=user_detail_view, name="detail"),
    # path("<str:username>/", view=user_detail_view, name="detail"),
]

mydjango/quora/urls.py
from django.urls import path

from mydjango.quora import views

app_name = "quora"

urlpatterns = [
    path("", views.QuestionListView.as_view(), name="all-questions"),
    path("correct-answered-questions", views.CorrectAnsweredQuestionListView.as_view(), name="correct-answered-questions"),
    path("uncorrect-answered-questions", views.UncorrectAnsweredQuestionListView.as_view(), name="uncorrect-answered-questions"),

]

mydjango/news/models.py
import uuid

from django.conf import settings
from django.db import models

# Create your models here.
class News(models.Model):
    uuid_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.SET_NULL,
                             related_name='publishes', verbose_name="用户")
    content = models.TextField(verbose_name="新闻内容")
    likers = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name="liked_news",
                                    verbose_name="点赞用户")
    reply = models.BooleanField(default=False, verbose_name="是否为评论")
    parent = models.ForeignKey("self", blank=True, null=True, on_delete=models.CASCADE,
                               related_name="children", verbose_name="父级自关联")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    updated_at = models.DateTimeField(auto_now=True,verbose_name="更新时间")

    class Meta:
        verbose_name = '新闻'
        verbose_name_plural = verbose_name
        ordering = ("-updated_at", "-created_at")

    def __str__(self):
        return self.content

    def switch_like(self, user):
        """点赞或者取消点赞"""
        if user in self.likers.all():
            self.likers.remove(user)
        else:
            self.likers.add(user)

    def get_parent(self):
        """返回自关联中的上级记录或者本身"""
        if self.parent:
            return self.parent
        else:
            return self

    def get_children(self):
        """获取当前记录的所有子记录"""
        parent = self.get_parent()
        return parent.children.all()

    def reply_this(self, user, text):
        """
        回复新闻的动态
        ：param user: 登录的用户
        ：param text: 回复的内容
        ：return: None
        """
        parent = self.get_parent()
        News.objects.create(
            user=user,
            content=text,
            reply=True,
            parent=parent
        )

    def likers_count(self):
        """点赞数"""
        return self.likers.count()

    def get_likers(self):
        """所有点赞用户"""
        return self.likers.all()

    def replies_count(self):
        """评论数量"""
        return self.get_children().count()

mydjango/blogs/forms.py
from django import forms
from mdeditor.fields import MDTextFormField
from mydjango.blogs.models import Article


class ArticleForm(forms.ModelForm):
    content = MDTextFormField()

    class Meta:
        model = Article
        fields = ['category', "title", "abstract", "content", "cover", "tags", "status"]

mydjango/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):

    error_message = admin_forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

mydjango/blogs/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView
from mydjango.blogs.forms import ArticleForm
from mydjango.blogs.models import Article, ArticleCategory
from mydjango.utils import AuthorRequiredMixin


class ArticleListView(ListView):
    """已发布的文章列表"""
    model = Article
    paginate_by = 5
    content_object_name = "article_list"
    template_name = "blogs/article_list.html"

    def get_queryset(self):
        return Article.objects.get_published()

    def get_context_data(self, *args, **kwargs):
        context = super(ArticleListView, self).get_context_data(*args, **kwargs)
        context['article_categories'] = ArticleCategory.objects.all()
        context['popular_tags'] = Article.objects.get_counted_tag()
        return context


class DraftListView(ArticleListView):

    def get_queryset(self, **kwargs):
        return Article.objects.get_drafts()

class ArticleCreateView(LoginRequiredMixin, CreateView):
    """创建文章"""
    model = Article
    form_class = ArticleForm
    template_name_suffix = "_create_form"
    template_name = "blogs/article_create_form.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ArticleCreateView, self).form_valid(form)

    # success_url = reverse_lazy('blogs:list')

    def get_success_url(self):
        message = "您的文章已经创建成功"
        messages.success(self.request,message)
        return reverse_lazy('blogs:list')

class ArticleDetailView(DetailView):
    """文章详情"""
    model = Article
    template_name =  'blogs/article_detail.html'
    context_object_name = 'article'

class ArticleUpdateView(LoginRequiredMixin, AuthorRequiredMixin, UpdateView):
    """用户更新文章"""
    model = Article
    form_class = ArticleForm
    template_name_suffix = "_update_form"
    template_name = "blogs/article_update_form.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ArticleUpdateView, self).form_valid(form)

    def get_success_url(self):
        message = "您的文章已经修改成功"
        messages.success(self.request,message)
        return reverse_lazy('blogs:detail', kwargs={'slug':self.get_object().slug})

mydjango/news/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseBadRequest, HttpResponse, JsonResponse
from django.shortcuts import render
from django.contrib.auth.decorators import  login_required
from django.template.loader import  render_to_string
from django.urls import reverse, reverse_lazy
from django.views.decorators.http import require_http_methods
# noinspection PyUnresolvedReferences
from mydjango.utils import ajax_required, AuthorRequiredMixin
# Create your views here.
from django.views.generic import ListView, DeleteView
from mydjango.news.models import News



class NewsListView(ListView):
    """新闻列表页"""
    # model = News
    # queryset = News.objects.filter(reply=False).all()
    paginate_by = 10
    template_name = "news/news_list.html"
    content_object_name = 'news_list'

    def get_queryset(self, *kwargs):
        return News.objects.filter(reply=False).all()

    # def get_context_data(self, *, object_list=None, **kwargs):
    #     context = super(NewsListView, self).get_context_data()
    #     context['importantNews'] = News
    #     return context

@login_required
@ajax_required
@require_http_methods(['POST'])
def post_news(request):
    """发送ajax post请求"""
    newsContent = request.POST['news_content'].strip()
    if newsContent:
        news = News.objects.create(user=request.user, content=newsContent)
        html = render_to_string('news/news_single.html', {'news': news, 'request': request})
        return HttpResponse(html)
    else:
        return HttpResponseBadRequest("内容不能为空！")

class NewDeleteView(LoginRequiredMixin, AuthorRequiredMixin, DeleteView):
    """删除一条新闻记录"""
    model = News
    template_name = 'news/news_confirm_delete.html'
    success_url = reverse_lazy('news:list')

@login_required
@ajax_required
@require_http_methods(['POST'])
def like(request):
    """点赞，相应ajax post请求"""
    news_id = request.POST['newsId']
    news = News.objects.get(pk=news_id)
    # 取消或者添加点赞
    news.switch_like(request.user)
    # 返回点赞数量
    return JsonResponse({"liker_count": news.likers_count()})

@login_required
@ajax_required
@require_http_methods(['POST'])
def post_reply(request):
    """发送回复ajax post请求"""
    print(request.POST['replyContent'])
    replyContent = request.POST['replyContent'].strip()
    parentId = request.POST['newsid']
    parent = News.objects.get(pk=parentId)
    # print(replyContent)
    if replyContent:
        parent.reply_this(request.user, replyContent)
        return JsonResponse({"newsid": parent.pk, "replies_count": parent.replies_count()})
    else:
        return HttpResponseBadRequest("内容不能为空！")

@ajax_required
@require_http_methods(['POST', 'GET'])
def get_replies(request):
    """返回新闻的评论"""
    news_id = request.GET['newsId']
    news = News.objects.get(pk=news_id)
    # render_to_string() 表示加载模板 填充数据，返回字符串
    replies_html = render_to_string("news/reply_list.html", {"replies": news.get_children()})
    # print(replies_html)
    return JsonResponse({
        "uuid": news_id,
        "replies_html": replies_html,
    })

mydjango/quora/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView
from mydjango.quora.models import Question


class QuestionListView(ListView):
    """所有问题列表"""
    model = Question
    paginate_by = 20
    context_object_name = 'questions-list'
    template_name = 'quora/question_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(QuestionListView, self).get_context_data()
        context["popular_tags"] = Question.objects.get_counted_tag()
        return context

class CorrectAnsweredQuestionListView(QuestionListView):
    """已有采纳答案的问题列表"""
    def get_queryset(self):
        return Question.objects.get_correct_answered()

class UncorrectAnsweredQuestionListView(QuestionListView):
    """还没有被采纳答案的问题列表"""
    def get_queryset(self):
        return Question.objects.get_uncoreect_answered()

mydjango/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    pk_url_kwarg = 'pk'
    template_name = 'users/user_detail.html'

user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["nickname", "job", "introduction", "avatar", "address", "birthday", "personal_url", "weibo", "zhihu", "github", "linkedin"]
    template_name = 'users/user_form.html'

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)
        # return self.request.user

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

mydjango/templates/blogs/article_create_form.html
{% extends "base.html" %}
{% load static crispy_forms_tags %}
{% block title %}
  修改文章|{{ block.super }}
{% endblock %}

{% block css %}
  {{ form.media }}
{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <form role="form" method="post" enctype="multipart/form-data" id="articleForm"
            action="{% url 'blogs:create' %}" style="width: 100%">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="form-group">
          <button type="submit" class="btn btn-primary publish">发表文章</button>
          {#          <button type="button" class="btn btn-default draft">保存草稿</button>#}
          <a class="btn btn-light " style="float:right" href="{% url 'blogs:list' %}">取消<a/>
        </div>
      </form>

    </div>
  </div>
{% endblock %}

{% block modal %}
{% endblock %}

{% block javascript %}
  <script>
    $(function () {
      $.get("{% static 'editormd_src/examples/test.md' %}",function (testmd) {
          $("#id_content").text(testmd);
      });
    });
  </script>
{% endblock %}

mydjango/templates/blogs/article_detail.html
{% extends 'base.html' %}
{% load static crispy_forms_tags comments  thumbnail %}
{% block title %}
  {{ article.title }}|{{ block.super }}
{% endblock %}

{% block css %}
  <link rel="stylesheet" href="{% static 'editormd_src/css/editormd.preview.css'%}" />
{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <!--title -->
        <h3 class="text-center">{{ article.title|title }}</h3>
        <hr/>
        <p class="text-left">
          <a href="{% url 'users:detail' article.user.username %}">{{ article.user.get_profile_name }}</a>
          发表于{{ article.created_at|date:"Y-m-d" }}
          {% if request.user.username == article.user.username %}|
            <a href="{% url 'blogs:update' article.pk %}" title="编辑文章">
              <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
              编辑文本
            </a>
          {% endif %} |
          <a href="#" class="ml-2">收藏本文</a>|
          <a href="#" class="ml-2">分享本文</a>
        </p>
        <hr/>
        <div id="test-editormd-view">
          <textarea id="markdown-textarea" style="display: block;"
                    name="test-editormd-markdown-doc">{{ article.content }}</textarea>
        </div>
        <hr/>
        {% get_comment_count for article as comment_count %}
        <h6>当前文章评论数: {{ comment_count }}</h6>
        <hr/>
        {#    {% render_comment_form for article %}#}
        {#    {% render_comment_form for article as form %}#}
        <div class="card my-4">
          <h5 class="card-header">评论</h5>
          <div class="card-body">
            {% if request.user.is_authenticated %}
              {% get_comment_form for article as form %}
              <form action="{% comment_form_target %}" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="hidden" name="next" value="{% url 'blogs:detail' article.slug %}"/>
                <input class="btn btn-info" type="submit" value="提交" id="id_submit"/>
              </form>
            {% endif %}
          </div>
        </div>
        <hr/>
        {% get_comment_list for article as comment_list %}
        {% for comment in comment_list %}
          <div class="media mb-4">
            {% thumbnail comment.user.avatar "x50" as im %}
              <img  src="{{ im.url }}" style="border-radius: 50%" alt="用户头像" class="align-self-start mr-3"/>
            {% empty %}
              <img src="{% static 'images/user.png' %}" style="border-radius: 50%;height: 100px"
                   class="align-self-start mr-3"
                   alt="没有头像"/>
            {% endthumbnail %}
          <div class="media-body">
            <h5 class="mt-0">{{ comment.user.get_profile_name }}</h5>
            {{ comment.comment }}
          </div>
          </div>
        {% endfor %}
      </div>
      <div class="col-md-4">
        <h6 class="card-header">文章目录</h6>
        <div class="card-body" style="padding: 8px" id="custom-toc-container"></div>
      </div>
    </div>
  </div>
{% endblock %}

{% block modal %}
{% endblock %}

{% block javascript %}
  <script src="{% static 'editormd_src/examples/js/jquery.min.js' %}"></script>
  <script src="{% static 'editormd_src/lib/marked.min.js' %}"></script>
  <script src="{% static 'editormd_src/lib/prettify.min.js' %}"></script>

  <script src="{% static 'editormd_src/lib/raphael.min.js' %}"></script>
  <script src="{% static 'editormd_src/lib/underscore.min.js' %}"></script>
  <script src="{% static 'editormd_src/lib/sequence-diagram.min.js' %}"></script>
  <script src="{% static 'editormd_src/lib/flowchart.min.js' %}"></script>
  <script src="{% static 'editormd_src/lib/jquery.flowchart.min.js' %}"></script>

  <script src="{% static 'editormd_src/editormd.js' %}"></script>
  <script type="text/javascript">
    $(function () {
      let testEditormdView = editormd.markdownToHTML("test-editormd-view", {
        markdown: $('#markdown-textarea').text(),//+ "\r\n" + $("#append-test").text(),
        //htmlDecode      : true,       // 开启 HTML 标签解析，为了安全性，默认不开启
        htmlDecode: "style,script,iframe",  // you can filter tags decode
        toc             : true,
        tocm: true,    // Using [TOCM]
        tocContainer    : "#custom-toc-container", // 自定义 ToC 容器层
        //gfm             : false,
        tocDropdown     : true,
        // markdownSourceCode : true, // 是否保留 Markdown 源码，即是否删除保存源码的 Textarea 标签
        emoji: true,
        taskList: true,
        tex: true,  // 默认不解析
        flowChart: true,  // 默认不解析
        sequenceDiagram: true,  // 默认不解析
      });
    });
  </script>
{% endblock %}

mydjango/templates/blogs/article_form.html
{% extends "base.html" %}
{% load static crispy_forms_tags %}
{% block title %}
  写文章|{{ block.super }}
{% endblock %}

{% block css %}
  {{ form.media }}
{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <form role="form" method="post" enctype="multipart/form-data" id="articleForm"
            action="{% url 'blogs:create' %}" style="width: 100%">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="form-group">
          <button type="submit" class="btn btn-primary publish">发表文章</button>
          {#          <button type="button" class="btn btn-default draft">保存草稿</button>#}
          <a class="btn btn-light " style="float:right" href="{% url 'blogs:list' %}">取消<a/>
        </div>
      </form>

    </div>
  </div>
{% endblock %}

{% block modal %}
{% endblock %}

{% block javascript %}
  <script>
    $(function () {
      $.get("{% static 'editormd_src/examples/test.md' %}",function (testmd) {
          $("#id_content").text(testmd);
      });
    });
  </script>
{% endblock %}

mydjango/templates/blogs/article_list.html
{% extends  'base.html' %}
{% load static thumbnail %}
{% block title %}
  博客文章列表页|{{ block.super }}
{% endblock %}
{% block css %}
{% endblock %}
{% block content %}
  <div class="container">
    <div class="card mt-3">
      <h5 class="card-header" style="padding: 4px"> 文章分类
        {% if request.user.is_authenticated %}
          <a class="btn-sm btn-primary pull-right" href="{% url 'blogs:drafts' %}" title="草稿箱">
            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>草稿箱</a>
          <a class="btn-sm btn-success pull-right mr-3" href="{% url 'blogs:create' %}" title="写文章">
            <i class="fa fa-pencil" aria-hidden="true"></i>写文章
          </a>
        {% else %}
          <small class="pull-right">登录后可以写文章</small>
        {% endif %}
      </h5>
      <div class="card-body" style="padding: 8px">
        {% for category in article_categories %}
          <a href="#" style="color: black">{{ category.catname }}</a>
        {% endfor %}
      </div>
    </div>
    <div class="row">
      <div class="col-md-8">
        <ul class="list-unstyled">
          {% for article in article_list %}
            <li class="media {% cycle '' 'my-4' %}">
              <a href="{% url 'blogs:detail' article.slug %}">
                {% thumbnail article.cover "280x400" as im %}
                  <img height="140" width="220" src="{{ im.url }}" alt="博客封面" class="mr-3"/>
                {% empty %}
                  <img height="140" width="220" src="{% static 'images/user.png' %}"
                       class="mr-3"
                       alt="没有封面"/>
                {% endthumbnail %}
              </a>
              <div class="media-body">
                <h5 class="mt-0 mb-1">
                  <a href="{% url 'blogs:detail' article.slug %}">{{ article.title }}</a>
                </h5>
                <p style="font-size: small">
                  {{ article.abstract|safe|truncatechars:80 }}
                </p>
                <div>标签：
                  {% for tag in article.tags.names %}
                    <a href="#"><span class="badge badge-info">{{ tag }}</span> </a>
                  {% endfor %}
                </div>
                <div class="text-muted">
                  <a href="{% url 'users:detail' article.user.username %}">{{ article.user.get_profile_name }}</a>
                  发表于 {{ article.created_at }}
                </div>
              </div>
            </li>
          {% endfor %}

        </ul>
      {% include "pagination.html" %}
      </div>
      <div class="col-md-4">
        <h6 class="card-header">标签云</h6>
        <div class="card-body">
          {% for tag,count in popular_tags %}
            <a href="#"><span class="badge badge-info">{{ tag }}({{ count }})</span></a>
          {% endfor %}
        </div>

      </div>
    </div>
  </div>
{% endblock %}
{% block modal %}
{% endblock %}
{% block javascript %}
{% endblock %}

mydjango/templates/blogs/article_update_form.html
{% extends "base.html" %}
{% load static crispy_forms_tags %}
{% block title %}
  修改文章|{{ block.super }}
{% endblock %}

{% block css %}
  {{ form.media }}
{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <form role="form" method="post" enctype="multipart/form-data" id="articleForm"
            action="{% url 'blogs:update' form.instance.pk %}" style="width: 100%">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="form-group">
          <button type="submit" class="btn btn-primary publish">修改文章</button>
          {#          <button type="button" class="btn btn-default draft">保存草稿</button>#}
          <a class="btn btn-light " style="float:right" href="{% url 'blogs:list' %}">取消<a/>
        </div>
      </form>

    </div>
  </div>
{% endblock %}

{% block modal %}
{% endblock %}

{% block javascript %}
{#  <script>#}
{#    $(function () {#}
{#      $.get("{% static 'editormd_src/examples/test.md' %}",function (testmd) {#}
{#          $("#id_content").text(testmd);#}
{#      });#}
{#    });#}
{#  </script>#}
{% endblock %}