config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # path("news/", TemplateView.as_view(template_name="pages/news.html"), name="news"),
    # path("blogs/", TemplateView.as_view(template_name="pages/blogs.html"), name="blogs"),
    # path("quora/", TemplateView.as_view(template_name="pages/quora.html"), name="quora"),
    path("chat/", TemplateView.as_view(template_name="pages/chat.html"), name="chat"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    ### 第三方路由
    re_path(r'mdeditor/', include('mdeditor.urls')),
    re_path(r'comments/', include('django_comments.urls')),
    # User management
    path("users/", include("mydjango.users.urls", namespace="users")),
    path("news/", include("mydjango.news.urls", namespace="news")),
    path("blogs/", include("mydjango.blogs.urls", namespace="blogs")),
    path("quora/", include("mydjango.quora.urls", namespace="quora")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

mydjango/blogs/urls.py
from django.urls import path
from django.views.generic import TemplateView

from mydjango.blogs import views

app_name = "blogs"

urlpatterns = [
    path("", views.ArticleListView.as_view(), name="list"),
    path("articel-creat/", views.ArticleCreateView.as_view(), name="create"),
    path("get-drafts/", views.DraftListView.as_view(), name="drafts"),
    path("article/<str:slug>/", views.ArticleDetailView.as_view(), name="detail"),
    path("article-update/<int:pk>/", views.ArticleUpdateView.as_view(), name="update"),
]

mydjango/news/urls.py
from django.urls import path

from mydjango.news import views

app_name = "news"

urlpatterns = [
    path("", views.NewsListView.as_view(), name="list"),
    path("post-news/", views.post_news, name="post_news"),
    path("delete/<str:pk>/", views.NewDeleteView.as_view(), name="delete_news"),
    path("like/", views.like, name="post_like"),
    path("post-reply/", views.post_reply, name="post_reply"),
    path("get-replies/", views.get_replies, name="get_replies"),
    # path("reply/", views.reply, name="post_reply"),
    # path("~redirect/", view=user_redirect_view, name="redirect"),
    # path("~update/", view=user_update_view, name="update"),
    # # path("<str:username>/", view=user_detail_view, name="detail"),
    # path("<str:username>/", view=user_detail_view, name="detail"),
]

mydjango/quora/urls.py
from django.urls import path

from mydjango.quora import views

app_name = "quora"

urlpatterns = [
    path("", views.QuestionListView.as_view(), name="all-questions"),
    path("correct-answered-questions", views.CorrectAnsweredQuestionListView.as_view(), name="correct-answered-questions"),
    path("uncorrect-answered-questions", views.UncorrectAnsweredQuestionListView.as_view(), name="uncorrect-answered-questions"),

]

mydjango/blogs/models.py
import uuid

from django.conf import settings
from django.db import models

# Create your models here.
from django.db.models import Count
from slugify import slugify

from taggit.managers import TaggableManager
from mdeditor.fields import MDTextField

# class ExampleModel(models.Model):
#     name = models.CharField(max_length=10)
#     content = MDTextField()

class ArticleCategory(models.Model):
    """定义文章类型"""
    catname = models.CharField(max_length=50, verbose_name="类别名称")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    updated_at = models.DateTimeField(auto_now=True, verbose_name="更新时间")

    def __str__(self):
        return self.catname

    class Meta:
        verbose_name = "文章类别"
        verbose_name_plural = verbose_name


class ArticleQuerySet(models.query.QuerySet):
    """自定义queryset ，提高模型的可用性"""

    def get_published(self):
        """返回已发表的文章"""
        return self.filter(status="P").order_by('-updated_at')

    def get_drafts(self):
        """返回草稿箱的文章"""
        return self.filter(status="D").order_by('-updated_at')

    def get_counted_tag(self):
        """返回已发表的文章中，每一个标签的数量(大于0的)"""
        tag_dict ={}
        query = self.filter(status="P").annotate(tagged=Count('tags')).filter(tags__gt=0)
        for obj in query:
            for tag in obj.tags.names():
                if tag not in tag_dict:
                    tag_dict[tag] = 1
                else:
                    tag_dict[tag] = -1
        return tag_dict.items()


class Article(models.Model):
    STATUS = (("D", "Draft"), ("P", "Published"))
    status = models.CharField(max_length=1, choices=STATUS, default='D', verbose_name="状态")
    category = models.ForeignKey(ArticleCategory, verbose_name="文章类别",
                                 null=True, blank=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, related_name="author",
                             on_delete=models.SET_NULL, verbose_name="作者")
    title = models.CharField(max_length=255, blank=False, null=False, unique=False, verbose_name="文章标题")
    cover = models.ImageField(upload_to="blogs/covers/%y/%m/%d", verbose_name="文章封面")
    abstract = models.CharField(max_length=255, null=True, blank=True, verbose_name="文章摘要", default="此文章还没有摘要")
    content = MDTextField(verbose_name="文章内容")
    slug = models.SlugField(max_length=255, null=True, blank=True, verbose_name="(url)别名")
    tags = TaggableManager(help_text="多个标签使用英文逗号(,)隔开", verbose_name="文章标签")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    updated_at = models.DateTimeField(auto_now=True, verbose_name="更新时间")

    objects = ArticleQuerySet.as_manager()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name

    def save(self, *args, **kwargs):
        if not self.slug:
            # 根据作者和标题生成文章url别名
            self.slug = slugify(self.title + self.user.username +"-" + uuid.uuid4().__str__()[0:8])

        super(Article, self).save(*args, **kwargs)

mydjango/blogs/forms.py
from django import forms
from mdeditor.fields import MDTextFormField
from mydjango.blogs.models import Article


class ArticleForm(forms.ModelForm):
    content = MDTextFormField()

    class Meta:
        model = Article
        fields = ['category', "title", "abstract", "content", "cover", "tags", "status"]

mydjango/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):

    error_message = admin_forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

mydjango/blogs/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView
from mydjango.blogs.forms import ArticleForm
from mydjango.blogs.models import Article, ArticleCategory
from mydjango.utils import AuthorRequiredMixin


class ArticleListView(ListView):
    """已发布的文章列表"""
    model = Article
    paginate_by = 5
    content_object_name = "article_list"
    template_name = "blogs/article_list.html"

    def get_queryset(self):
        return Article.objects.get_published()

    def get_context_data(self, *args, **kwargs):
        context = super(ArticleListView, self).get_context_data(*args, **kwargs)
        context['article_categories'] = ArticleCategory.objects.all()
        context['popular_tags'] = Article.objects.get_counted_tag()
        return context


class DraftListView(ArticleListView):

    def get_queryset(self, **kwargs):
        return Article.objects.get_drafts()

class ArticleCreateView(LoginRequiredMixin, CreateView):
    """创建文章"""
    model = Article
    form_class = ArticleForm
    template_name_suffix = "_create_form"
    template_name = "blogs/article_create_form.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ArticleCreateView, self).form_valid(form)

    # success_url = reverse_lazy('blogs:list')

    def get_success_url(self):
        message = "您的文章已经创建成功"
        messages.success(self.request,message)
        return reverse_lazy('blogs:list')

class ArticleDetailView(DetailView):
    """文章详情"""
    model = Article
    template_name =  'blogs/article_detail.html'
    context_object_name = 'article'

class ArticleUpdateView(LoginRequiredMixin, AuthorRequiredMixin, UpdateView):
    """用户更新文章"""
    model = Article
    form_class = ArticleForm
    template_name_suffix = "_update_form"
    template_name = "blogs/article_update_form.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ArticleUpdateView, self).form_valid(form)

    def get_success_url(self):
        message = "您的文章已经修改成功"
        messages.success(self.request,message)
        return reverse_lazy('blogs:detail', kwargs={'slug':self.get_object().slug})

mydjango/news/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseBadRequest, HttpResponse, JsonResponse
from django.shortcuts import render
from django.contrib.auth.decorators import  login_required
from django.template.loader import  render_to_string
from django.urls import reverse, reverse_lazy
from django.views.decorators.http import require_http_methods
# noinspection PyUnresolvedReferences
from mydjango.utils import ajax_required, AuthorRequiredMixin
# Create your views here.
from django.views.generic import ListView, DeleteView
from mydjango.news.models import News



class NewsListView(ListView):
    """新闻列表页"""
    # model = News
    # queryset = News.objects.filter(reply=False).all()
    paginate_by = 10
    template_name = "news/news_list.html"
    content_object_name = 'news_list'

    def get_queryset(self, *kwargs):
        return News.objects.filter(reply=False).all()

    # def get_context_data(self, *, object_list=None, **kwargs):
    #     context = super(NewsListView, self).get_context_data()
    #     context['importantNews'] = News
    #     return context

@login_required
@ajax_required
@require_http_methods(['POST'])
def post_news(request):
    """发送ajax post请求"""
    newsContent = request.POST['news_content'].strip()
    if newsContent:
        news = News.objects.create(user=request.user, content=newsContent)
        html = render_to_string('news/news_single.html', {'news': news, 'request': request})
        return HttpResponse(html)
    else:
        return HttpResponseBadRequest("内容不能为空！")

class NewDeleteView(LoginRequiredMixin, AuthorRequiredMixin, DeleteView):
    """删除一条新闻记录"""
    model = News
    template_name = 'news/news_confirm_delete.html'
    success_url = reverse_lazy('news:list')

@login_required
@ajax_required
@require_http_methods(['POST'])
def like(request):
    """点赞，相应ajax post请求"""
    news_id = request.POST['newsId']
    news = News.objects.get(pk=news_id)
    # 取消或者添加点赞
    news.switch_like(request.user)
    # 返回点赞数量
    return JsonResponse({"liker_count": news.likers_count()})

@login_required
@ajax_required
@require_http_methods(['POST'])
def post_reply(request):
    """发送回复ajax post请求"""
    print(request.POST['replyContent'])
    replyContent = request.POST['replyContent'].strip()
    parentId = request.POST['newsid']
    parent = News.objects.get(pk=parentId)
    # print(replyContent)
    if replyContent:
        parent.reply_this(request.user, replyContent)
        return JsonResponse({"newsid": parent.pk, "replies_count": parent.replies_count()})
    else:
        return HttpResponseBadRequest("内容不能为空！")

@ajax_required
@require_http_methods(['POST', 'GET'])
def get_replies(request):
    """返回新闻的评论"""
    news_id = request.GET['newsId']
    news = News.objects.get(pk=news_id)
    # render_to_string() 表示加载模板 填充数据，返回字符串
    replies_html = render_to_string("news/reply_list.html", {"replies": news.get_children()})
    # print(replies_html)
    return JsonResponse({
        "uuid": news_id,
        "replies_html": replies_html,
    })

mydjango/quora/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView
from mydjango.quora.models import Question


class QuestionListView(ListView):
    """所有问题列表"""
    model = Question
    paginate_by = 20
    context_object_name = 'questions-list'
    template_name = 'quora/question_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(QuestionListView, self).get_context_data()
        context["popular_tags"] = Question.objects.get_counted_tag()
        return context

class CorrectAnsweredQuestionListView(QuestionListView):
    """已有采纳答案的问题列表"""
    def get_queryset(self):
        return Question.objects.get_correct_answered()

class UncorrectAnsweredQuestionListView(QuestionListView):
    """还没有被采纳答案的问题列表"""
    def get_queryset(self):
        return Question.objects.get_uncoreect_answered()

mydjango/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    pk_url_kwarg = 'pk'
    template_name = 'users/user_detail.html'

user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["nickname", "job", "introduction", "avatar", "address", "birthday", "personal_url", "weibo", "zhihu", "github", "linkedin"]
    template_name = 'users/user_form.html'

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)
        # return self.request.user

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

mydjango/templates/base.html
{% load static i18n compress thumbnail%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Wendell{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Behold My Awesome Project!">
    <meta name="author" content="wendell">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
{#      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>#}
        <script src="{% static 'js/html5shiv.min.js' %}"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">


    {% compress css %}
      <!-- Latest compiled and minified Bootstrap CSS -->
      {#    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">#}
      <link href="{% static 'bootstrap-4.3.1-dist/css/bootstrap.min.css' %}" rel="stylesheet">
      <link href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet">
      <!-- Your stuff: Third-party CSS libraries go here -->

      <!-- This file stores project-specific CSS -->

      <link href="{% static 'css/project.css' %}" rel="stylesheet">
      {% block css %}{% endblock %}
    {% endcompress %}


  </head>

  <body>

  <div class="mb-1">
    {#      <nav class="navbar navbar-expand-md navbar-light bg-light">#}
    {#        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">#}
    {#          <span class="navbar-toggler-icon"></span>#}
    {#        </button>#}
    {#        <a class="navbar-brand" href="{% url 'home' %}">Wendell</a>#}
    {##}
    {#        <div class="collapse navbar-collapse" id="navbarSupportedContent">#}
    {#          <ul class="navbar-nav mr-auto">#}
    {#            <li class="nav-item active">#}
    {#              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>#}
    {#            </li>#}
    {#            <li class="nav-item">#}
    {#              <a class="nav-link" href="{% url 'about' %}">About</a>#}
    {#            </li>#}
    {#            {% if request.user.is_authenticated %}#}
    {#              <li class="nav-item">#}
    {# URL provided by django-allauth/account/urls.py #}
    {#                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>#}
    {#              </li>#}
    {#              <li class="nav-item">#}
    {# URL provided by django-allauth/account/urls.py #}
    {#                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>#}
    {#              </li>#}
    {#            {% else %}#}
    {#              <li class="nav-item">#}
    {# URL provided by django-allauth/account/urls.py #}
    {#                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>#}
    {#              </li>#}
    {#              <li class="nav-item">#}
    {# URL provided by django-allauth/account/urls.py #}
    {#                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>#}
    {#              </li>#}
    {#            {% endif %}#}
    {#          </ul>#}
    {#        </div>#}
    {#      </nav>#}
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'home' %}">Wendell</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active" id="home">
            <a class="nav-link" href="{% url 'home' %}">首 页<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item" id="about">
            <a class="nav-link" href="{% url 'about' %}">关 于</a>
          </li>
          <li class="nav-item active" id="news">
            <a class="nav-link" href="{% url 'news:list' %}">新闻动态<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active" id="blogs">
            <a class="nav-link" href="{% url 'blogs:list' %}">博客文章<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active" id="quora">
            <a class="nav-link" href="{% url 'quora:all-questions' %}">有问必答<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active" id="chat">
            <a class="nav-link" href="{% url 'chat' %}">在线聊天<span class="sr-only">(current)</span></a>
          </li>

          {% if request.user.is_authenticated %}
            <li class="nav-item" id="users">
              {#                 URL provided by django-allauth/account/urls.py #}
              <a class="nav-link" href="{% url 'users:detail' request.user.username %}">
                {% thumbnail request.user.avatar "x20" as im %}
                    <img src="{{ im.url }}" style="border-radius: 50%;" alt="用户头像" class="user-image"/>
                {% empty %}
                    <img src="{% static 'images/user.png' %}" height="25px" alt="没有头像" />
                {% endthumbnail %}
                {#                <img src="{{ MEDIA_URL }}{{ request.user.avatar }}" style="width:20px;height:20px"></a>#}
              </a>
            </li>
            <li class="nav-item" id="logout">
              {#                 URL provided by django-allauth/account/urls.py #}
              <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
            </li>
          {% else %}
            <li class="nav-item" id="sigup">
              {#                 URL provided by django-allauth/account/urls.py #}
              <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
            </li>
            <li class="nav-item" id="login">
              {#                 URL provided by django-allauth/account/urls.py #}
              <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
            </li>
          {% endif %}

          {#                <a class="dropdown-item" href="#">Something else here</a>#}

        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
  </div>

  <div class="container">

    {% if messages %}
      {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                  aria-hidden="true">&times;</span></button>
        </div>
      {% endfor %}
    {% endif %}

    {% block content %}
      <p>Use this document as a way to quick start any new project.</p>
    {% endblock content %}

  </div> <!-- /container -->

  {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->


      <!-- Bootstrap JS and its dependencies-->
{#      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>#}
{#      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>#}
{#      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>#}

      <!-- Your stuff: Third-party javascript libraries go here -->


      <!-- place project specific Javascript in this file -->
    {% compress js %}
      <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'bootstrap-4.3.1-dist/js/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/project.js' %}"></script>
      <script>
        const currentUser = "{{ request.user.username }}";
        $(function () {
          let flags = ['news', 'about', 'blogs', 'quora', 'chat', 'sigup', 'login', 'users', 'logout'];
          let href = window.location.href;
          let isHone = true;
          flags.forEach(function (item) {
            if (href.indexOf(item) !== -1) {
              $('#' + item).addClass('active');
              isHome = false;
            } else {
              $('#' + item).removeClass('active');
            }
          });
          if (isHome) {
            $('#home').addClass('active');
          }
        });
      </script>
      {% block javascript %}
      {% endblock javascript %}
    {% endcompress %}

  </body>
</html>

mydjango/templates/pagination.html
{% if is_paginated %}
  <nav aria-label="Topics pagination" class="mb-4">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">上一页</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">上一页</span>
        </li>
      {% endif %}

      {% for page_num in paginator.page_range %}
        {% if page_obj.number == page_num %}
          <li class="page-item active">
            <span class="page-link">
              {{ page_num }}
              <span class="sr-only">（当前页）</span>
            </span>
          </li>
        {% elif page_num > page_obj.number|add:'-3' and page_num < page_obj.number|add:'3' %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">下一页</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">下一页</span>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}